#ifndef QFAKTURYDBCORE_GLOBAL_H
#define QFAKTURYDBCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QFAKTURYDBCORE_LIBRARY)
#  define QFAKTURYDBCORE_EXPORT Q_DECL_EXPORT
#else
#  define QFAKTURYDBCORE_EXPORT Q_DECL_IMPORT
#endif

#endif // QFAKTURYDBCORE_GLOBAL_H
